### ISSUE TITLE
psl.pqube.DEVICEID

### ISSUE THREAD

**Issue by pingthings** [BTrDB/btrdb-server#43]
The current implementation expects that the device will always be defined as psl.pqube.DEVICEID which is not optimal considering device may not be a pqube etc.  

In manifest:
add psl.pqube.p300001 path=myDevice

I like the idea of the dot notation for the name for logical groupings or as a label.

**Comment by immesys** [comment]
That's not quite correct. You can add any names, it just must be psl.pqube.ID if you want the pqube driver to load the data. You can add other devices with other names but then you must write your own drivers for them.

**Comment by pingthings** [comment]
Didn't realize that was representative of a driver name...  which now opens up additional questions and documentation requirements.  Thanks for clarifying that device label requirements.

**Comment by immesys** [comment]
It's not really referring to the driver, its more that the name should be <vendor>.<product>.<id> and drivers may filter based on which vendors and products they support
