### ISSUE TITLE
How to replace the kubernetes controller manager container using minikube

### ISSUE THREAD

**Issue by hcs129** [BTrDB/btrdb-server#46]
I'm installing the BTrDB on my laptop, using ceph/daemon and minikube as suggested, following the instruction in
[https://docs.smartgrid.store/prerequisites.html#connecting-kubernetes-to-ceph.](url)

For kubeadm
> edit the file /etc/kubernetes/manifests/kube-controller-manager.json. In that file, change the specified image to btrdb/kubernetes-controller-manager-rbd:1.6.2

However, I cannot find the equivalent configure file for minikube.  Any suggestion for this?

Thanks

**Comment by pingthings** [comment]
You should be able to use kubectl to replace the running image.  An example from the command line would look something like:

kubectl get pod mypod -o yaml | sed 's/\(image: myimage\):.*$/\1:v4/' | kubectl replace -f -

Make sure you replace the reference to mypod with the kube-controller-manager name as listed in kubectl get pods --all-namespaces -o wide

An alternative is that you could also pull the configuration into a .yaml file, modify the image: tag with your favorite editor and then issue a kubectl create -f  whateveryounamed.yaml

An example to pull the yaml would look like:
kubectl get pod -n kube-system kube-controller-manager-XXXX -o=yaml

**Comment by hcs129** [comment]
Hi
Many thanks for your suggestion.  I have pull a .yaml and modify the image:tag to btrdb version then kubectl replace -f- the .yaml.
Again I use kubectl get pod -n kube-system kube-controller-manager-XXXX -o=yaml. Here's my output. I'm not sure if it has been successfully done because the second image is still "image: gcr.io/google-containers/kube-addon-manager:v6.4-beta.1".

> apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 8538d869917f857f9d157e66b059d05b
    kubernetes.io/config.mirror: 8538d869917f857f9d157e66b059d05b
    kubernetes.io/config.seen: 2017-08-10T11:05:51.335804409Z
    kubernetes.io/config.source: file
  creationTimestamp: 2017-08-10T11:05:56Z
  labels:
    component: kube-addon-manager
    kubernetes.io/minikube-addons: addon-manager
    version: v6.4
  name: kube-addon-manager-minikube
  namespace: kube-system
  resourceVersion: "57997"
  selfLink: /api/v1/namespaces/kube-system/pods/kube-addon-manager-minikube
  uid: e21e1549-7dbb-11e7-8bc6-08002767ecd0
spec:
  containers:
  - image: btrdb/kubernetes-controller-manager-rbd:1.6.2
    imagePullPolicy: IfNotPresent
    name: kube-addon-manager
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: addons
      readOnly: true
  dnsPolicy: ClusterFirst
  hostNetwork: true
  nodeName: minikube
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/
    name: addons
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-08-10T11:05:56Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-08-11T07:07:57Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-08-11T07:07:55Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b102520017cd444f74f40deb22f54e24de6976cf8e87c823fab5d84de65e263c
    image: gcr.io/google-containers/kube-addon-manager:v6.4-beta.1
    imageID: docker://sha256:85809f3181235c56167f3da75b035ef065a5214b870de57da823020d642670e3
    lastState:
      terminated:
        containerID: docker://e6c55b7d783e024a3b800b5815cc075eca4f56c5d1678022259f71ac9fd17915
        exitCode: 0
        finishedAt: 2017-08-11T07:07:34Z
        reason: Completed
        startedAt: null
    name: kube-addon-manager
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: 2017-08-11T07:07:56Z
  hostIP: 192.168.99.100
  phase: Running
  podIP: 192.168.99.100
  qosClass: Burstable
  startTime: 2017-08-10T11:05:56Z

**Comment by hcs129** [comment]
One more question is that how to use the "avoid storage class" option in the site config for minikube according to the install tutorial.

**Comment by hcs129** [comment]
Here is the output when I check the information of testclaim.yaml

> Name:        testclaim
> Namespace:    default
> StorageClass:    fastrbd
> Status:        Pending
> Volume:        
> Labels:        <none>
> Annotations:    kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"testclaim","namespace":"default"},"spec":{"accessModes":["ReadWr...
>         volume.beta.kubernetes.io/storage-class=fastrbd
>         volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
> Capacity:    
> Access Modes:    
> Events:
>   FirstSeen    LastSeen    Count    From                SubObjectPath    Type        Reason            Message
>   ---------    --------    -----    ----                -------------    --------    ------            -------
>   11s        9s        2    persistentvolume-controller            Warning        ProvisioningFailed    Failed to provision volume with StorageClass "fastrbd": rbd: create volume failed, err: executable file not found in $PATH

**Comment by pingthings** [comment]
So, you don't need to worry about the second image: gcr.io/google-containers/kube-addon-manager:v6.4-beta.1 line in the .yaml.   It's just the kube-controller-manager that needed to be swapped out.

I can't answer the "avoid storage class" issue and will defer to @immesys since he wrote the original documentation for the development environment and we've concentrated primarily on full cluster installs on bare metal.  We will update the documentation to reflect any insights he can give you.

I would suggest the error that you are receiving is potentially generated due to the discrepancy with minikube and storage class when it comes to CEPH.   @immesys ?

**Comment by hcs129** [comment]
I search the error in google. It seems that the rror

> rbd: create volume failed, err: executable file not found in $PATH
is related to ceph-common. It is suggested that to install the ceph-common on every node of kubernetes. Since we use minikube, apt-get is not suppoted on the virtual node 'minkube'. I use 'minikube ssh' to log the node but still unable to install the ceph-common.

**Comment by immesys** [comment]
Closing this, we no longer recommend minikube (rather use the devmachine script)
