### ISSUE TITLE
BTrDB Single Node Installation

### ISSUE THREAD

**Issue by gtfierro** [BTrDB/btrdb-server#50]
We are working on a single-node installation of BTrDB. We have gotten the basic Ceph installation from https://docs.smartgrid.store/ working (from the Prerequisites section), but we are having trouble finding a good guide for installing kubernetes on a single node, as well as knowing which features we need to look at installing (e.g. do we need 'flannel' for networking?). Can you recommend one?

**Comment by pingthings** [comment]
Gabe,  I've worked through a number of scenarios and have pretty much settled on a minikube+rook.io setup for single node installations.   Minikube can work in a number of different nodes depending on your host platform.  The installation that I got operational and rather quickly including the Ceph component was on an Ubuntu 16.04 box with a boot drive and an additional single 500GB SSD using VirtualBox which is the native option in minikube.   Rook.io is the piece that I've come to really appreciate which is a containerized version of CEPH on K8s.  Hit me up on the slack channels if you need help or have questions.   I haven't finished writing up the documentation yet and it is meant to replace the existing development install in docs.smartgrid.store.

**Comment by gtfierro** [comment]
Thanks! I will definitely take a look at rook.io in the future, but we were able to successfully install ceph on the server.

Regarding kubernetes, we had a few issues with installing minikube, but I'll leave discussion of that to my colleague @aslakjohansen, who is installing BTrDB at SDU in Denmark

**Comment by pingthings** [comment]
Alternatively, there is another install that I have been playing with that you could try if you're on Ubuntu.  It uses LXC and it's pretty much a click install.  Do a snap install of LXD and then do a snap install of conjure-up.  https://conjure-up.io  There is a canonical installation for kubernetes that you can apply to localhost.  Check out https://insights.ubuntu.com/2017/11/13/how-to-deploy-one-or-more-kubernetes-clusters-to-a-single-box/?_ga=2.108191617.267919853.1510616699-818517769.1510616699

I've tried this and it works pretty well.
