### ISSUE TITLE
BTrDB use case for irregular interval time series

### ISSUE THREAD

**Issue by georgew5656** [BTrDB/btrdb-server#52]
We are considering migrating time series data from mongoDB to BTrDB and trying to understand whether the peculiarities of our data will be supported.

The time series data comes on irregular intervals between 30 seconds up to a few minutes. Additionally, each key is mapped to a vector value within each time series.

**Comment by immesys** [comment]
The irregularity of the data is not a problem. We don't directly support vector data though. A lot of our data is intrinsically a vector but we unwrap it into scalar streams (e.g a vector of 3 numbers becomes 3 distinct streams).

In general I recommend BTrDB when you have very dense streams (e.g >10Hz, up to 1Khz) or when you require very fast aggregate queries within a stream (e.g years of 1khz data and you want to find all places where it crossed a threshold).
