### ISSUE TITLE
make fails; dep not found

### ISSUE THREAD

**Issue by ChristophGehbauer** [BTrDB/btrdb-server#54]
Hello developer team,
I wanted to install the btrdb-server on Ubuntu 16.04, but the make process fails with in the step:
cd $(GOPATH)/src/github.com/BTrDB/btrdb-server &&  dep ensure
and fails with:
/bin/sh: 1: dep: not found
Please can you let me know what could be the issue and which other OS would be preferred?
Thank you,
Christoph

**Comment by immesys** [comment]
dep is provided by go-dep `https://github.com/golang/dep`
