### ISSUE TITLE
Changes in V5

### ISSUE THREAD

**Issue by FilipJanitor** [BTrDB/btrdb-server#58]
Hi, I noticed that development of version 5 is in progress now. Could you please shed some light on what to expect from the new version? Are there any major feature additions, architecture or API changes planned?
Thanks!

**Comment by immesys** [comment]
The primary differences are:

- A change to how stream metadata is stored and queried. Many customers have expressed a need for full SQL queries of stream metadata. These features will be rolling out throughout the next few months, we are just adding support for those features now.
- A change to the binary format of streams in storage. We now have even better compression. Again, more features that take advantage of the new disk format will be announced over the next few months.
- The addition of standard deviation to statistical queries
- Minor changes to the API to add support for new features. Most programs will not need significant changes as they move to V5

When V5 is released we will have a more concrete list of changes. Right now we are busy determining which features make it in and which do not.
