### ISSUE TITLE
server crash on restart

### ISSUE THREAD

**Issue by lilvinz** [BTrDB/btrdb-server#59]
I had to restart a server pod, which did not work.

The process did not shut down. So i had to kill it.

When trying to start it again, the server crashes during journal checking after emitting "panic: (404: stream does not exist)"

I have put the ceph pools aside so i could provide them for further analysis.

[logs-from-btrdb-in-btrdb-0 .txt](https://github.com/BTrDB/btrdb-server/files/2639103/logs-from-btrdb-in-btrdb-0.txt)

**Comment by immesys** [comment]
Hi

BTrDB is expected to take some time to shut down if you have been performing small synchronous writes. The write coalescence engine needs to commit all of that to main storage. You can force a shutdown but that will just make the startup of the replacing pod a little slower.

You hit a known bug where you obliterated a stream that had been performing small inserts and still had journal entries remaining. If you change your btrdb pod image to `btrdb/db:4.15.7` the issue should be fixed.

Thanks for reporting

**Comment by lilvinz** [comment]
Thank, that did the trick!
