### ISSUE TITLE
How to install btrdb?

### ISSUE THREAD

**Issue by smallnine9** [BTrDB/btrdb-server#64]
I am sorry to ask a so naive question, I am a beginner of golang, and after I install the go 1.12 in my ubuntu , I just use command “make” to make this btrdb project, but i receive a error message:
```
hadoop@ubuntu:~/Desktop/btrdb-server-master$ sudo make
mkdir -p /home/hadoop/Desktop/btrdb-server-master/build/gopath/bin
go get -u github.com/golang/dep/cmd/dep
cd /home/hadoop/Desktop/btrdb-server-master/build/gopath/src/github.com/BTrDB/btrdb-server &&  dep ensure
/bin/sh: 1: dep: not found
Makefile:23: recipe for target '/home/hadoop/Desktop/btrdb-server-master/build/gopath/src/github.com/BTrDB/btrdb-server/vendor' failed
make: *** [/home/hadoop/Desktop/btrdb-server-master/build/gopath/src/github.com/BTrDB/btrdb-server/vendor] Error 127

```
and i do not know why this happen, if I want to use btrdb and get intuitive grasp,how should I do? please help me ,thank you

**Comment by immesys** [comment]
To build BTrDB you would typically run

```
cd btrdbd
go build
```

But before you do that, you need to populate the vendor directory by running

```
go get -u github.com/golang/dep/cmd/dep
dep ensure
```

Just building BTrDB is only the first step however. It is a part of a larger system and there are components such as ceph, etcd, etc that also need to be installed.

There is a super easy to use commercial BTrDB PaaS offering (https://pingthings.io/) that also includes a bunch of newer features, better compression and an analytics library. The original open-source stack is documented here (https://docs.smartgrid.store/) although you need to be pretty good at kubernetes to get that up and running.
