### ISSUE TITLE
Running on local machine

### ISSUE THREAD

**Issue by fsolleza** [BTrDB/btrdb-server#70]
Hi!

I'm curious how to set this up to run on a local machine?

Thanks!

**Comment by fsolleza** [comment]
I think I just figured it out. Thanks nonetheless!

**Comment by immesys** [comment]
@fsolleza if you are interested in doing benchmarking, perhaps ping @looselycoupled at PingThingsIO. They did some work on using the timescale benchmark suite to benchmark BTrDB. The file storage commit is waaay to far back in time to use.
